/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#3e3f45",
        "surface-container-high": "#e2e9ec",
        "error-container": "#fe8983",
        "surface-tint": "#005ac2",
        "on-secondary-container": "#505157",
        "surface-container": "#eaeff1",
        "on-background": "#2b3437",
        "inverse-primary": "#4d8eff",
        "surface-container-lowest": "#ffffff",
        "surface": "#f8f9fa",
        "on-secondary": "#f9f8ff",
        "tertiary-fixed": "#d3ceef",
        "on-primary-fixed-variant": "#0057bd",
        "inverse-on-surface": "#9b9d9e",
        "on-error-container": "#752121",
        "on-error": "#fff7f6",
        "outline": "#737c7f",
        "primary-container": "#d8e2ff",
        "surface-container-low": "#f1f4f6",
        "primary-fixed-dim": "#c3d4ff",
        "on-tertiary-fixed-variant": "#504e69",
        "secondary-dim": "#515359",
        "secondary-fixed": "#e2e2e9",
        "on-tertiary-fixed": "#34314b",
        "error-dim": "#4e0309",
        "on-primary-container": "#004eaa",
        "error": "#9f403d",
        "secondary-fixed-dim": "#d4d4db",
        "secondary": "#5e5f65",
        "on-secondary-fixed-variant": "#5a5b61",
        "primary-dim": "#004fab",
        "inverse-surface": "#0c0f10",
        "outline-variant": "#abb3b7",
        "on-tertiary": "#fcf7ff",
        "surface-dim": "#d1dce0",
        "tertiary-dim": "#53506b",
        "tertiary-container": "#d3ceef",
        "on-primary": "#f7f7ff",
        "primary-fixed": "#d8e2ff",
        "on-surface-variant": "#586064",
        "tertiary": "#5f5c78",
        "surface-variant": "#dbe4e7",
        "on-primary-fixed": "#003c86",
        "surface-container-highest": "#dbe4e7",
        "tertiary-fixed-dim": "#c5c0e0",
        "primary": "#005ac2",
        "on-surface": "#2b3437",
        "background": "#f8f9fa",
        "secondary-container": "#e2e2e9",
        "on-tertiary-container": "#47445f",
        "surface-bright": "#f8f9fa"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "full": "9999px"
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
